### ISSUE TITLE
Sracunavanje statistike

### ISSUE THREAD

**Issue by milekicnikola** [milekicnikola/JSD#11]

**Comment by kimi131189** [comment]
Statistika se sracunava unutar modela kroz funkcije koje se potom pozivaju iz html template generatora. Dovoljno je samo da ispunis model sa podatcima tipa - igrac taj i dao 5 FG, promasio 7, model ce to odmah sracunati u procentima ako treba i na html-u takodje outputovati FG 5/12.

Slicno kako sam radio za Player Performance Index Rating unutar Player klase.
